### ISSUE TITLE
_index.json file path exposed in url

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/foundationskillstraining#2]
There is an usual behaviour of the index being exposed in the rendered url see below.

<img width="1440" alt="Screen Shot 2023-09-10 at 3 18 57 pm" src="https://github.com/jamestagal/foundationskillstraining/assets/6309595/3b50265b-6e27-48d6-a876-7f3ea3c6ef43">

**Comment by jimafisk** [comment]
Your theme looks really nice!

The name that appears in the browser tab is from the `<title>` tag in your `<head>`. I just made an adjustment (https://github.com/jamestagal/foundationskillstraining/commit/4ae4d9f60e4710133a20420b4cd818b9c63b7838) so it looks for a `meta.title` field in your content source, and has a fallback if it can't find one.

**Comment by jamestagal** [comment]
hi @jimafisk 
Thanks for that fix. I think the title field must have been in the bare Plenti project and I forgot to look at it. 😃 

BTW. I bought a commercial licence when purchasing this template so I will make it available as a Plenti theme after I finish building it.
The licences covers:

Correction  - my first reply here was not correct. Below is the commercial licence:

- use the theme/template to create up to 5 end products for your clients;

- modify or manipulate the item, or combine it with other items in a way that meets your client’s needs;

- the client can modify website templates and themes, combining them with other pieces to suit the end product.

You can read more [here](https://www.templatemonster.com/licenses/website-templates/)

So it looks like there is a limit on it.

**Comment by jimafisk** [comment]
Ahh ok, if there is a limit on the uses we probably can't reference as a theme on plenti.co. It's still a nice theme for your company though!
