### ISSUE TITLE
Help with error - gh-pages deploy

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/foundationskillstraining#3]
Hi @jimafisk 

I am trying to deploy this site to a temporary url on github pages and used the workflow configuration of another Plenti site but I am getting the following error.

```terminal

Error: .github#L1actions/checkout@v2 and docker://plentico/plenti:latest are not allowed to be used in jamestagal/foundationskillstraining. Actions in this workflow must be: within a repository owned by jamestagal or matching the following: JamesIves/github-pages-deploy-action@releases/v3.Show less
--


Annotations
1 error
[Error: .github#L1](https://github.com/jamestagal/foundationskillstraining/commit/a0a2c2d86bdae07771c0a9318a34ffe8b7fa6db9#annotation_15003273712)
actions/checkout@v2 and docker://plentico/plenti:latest are not allowed to be used in jamestagal/foundationskillstraining. Actions in this workflow must be: within a repository owned by jamestagal or matching the following: JamesIves/github-pages-deploy-action@releases/v3.
```

I have the following set up in the repo's action page because I see an action with someone else's name so I added that.
<img width="1157" alt="Screen Shot 2023-10-19 at 9 14 05 am" src="https://github.com/jamestagal/foundationskillstraining/assets/6309595/0339cd89-0a7d-4282-9639-4ea185eabdbe">

This is the first time to do this via Github page so I am unsure. Pls suggest a fix. 😸 
Cheers,
Ben

**Comment by jimafisk** [comment]
I haven't run into that before, can you just select the first option to "allow all actions" and see if that clears it up?

**Comment by jimafisk** [comment]
Looks like you might have figured this out? https://github.com/jamestagal/foundationskillstraining/commit/a0a2c2d86bdae07771c0a9318a34ffe8b7fa6db9

**Comment by jamestagal** [comment]
Hi @jimafisk 
Yes I changed that back to the original setting there. But I think it might have been the Workflow Permissions setting needed to be read/write. So I that fine and I now get a green check so it succeeded but still not seeing the site live. Does it take any length of time to be visible?

BTW - on this last deploy attempt I only got a warning message about node12 being deprecated :
```terminal
[deploy](https://github.com/jamestagal/foundationskillstraining/actions/runs/6569005462/job/17844370404)
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, JamesIves/github-pages-deploy-action@releases/v3. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
Thanks for responding.

**Comment by jamestagal** [comment]
Here is the page: https://jamestagal.github.io/foundationskillstraining/

**Comment by jimafisk** [comment]
What do you have in `Settings > Pages` on GitHub? Deploy from a branch and then select `gh-pages` branch using `/ (root)`?

You can bump your node version to something newer, although I don't see that in your build script (https://github.com/jamestagal/foundationskillstraining/blob/main/.github/workflows/gh-pages.yml). Is this just a dependency of JamesIves?

**Comment by jamestagal** [comment]
Thanks @jimafisk yes I had it on a branch not ```gh-pages``` branch so that fixed the deploy and is now live. thanks.

About the ```gh-pages``` workflow I just copied over the same setting you have in other themes so I don't know what  that is ...Jameslves etc... 😸  Can I just add to it? the a node version something like the following.

```yml
 - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
```

**Comment by jimafisk** [comment]
If you're not building in additional NPM packages, you can avoid adding the node setup step. Also version 16 is old at this point too, I think they're on 20.
